DM-3534 DM-3561: Add Events and News Components
department-of-veterans-affairs/diffusion-marketplace pull request #544
Opened 2022-09-27 18:04 UTC by camillevilla

### JIRA issue link
[DM-3534: Events](https://agile6.atlassian.net/browse/DM-3534?atlOrigin=eyJpIjoiZThlYjYzYWUwMTdlNDliM2FhZDk2NTk5NDRiZTUyYzQiLCJwIjoiaiJ9
)
[DM-3561: News](https://agile6.atlassian.net/browse/DM-3561?atlOrigin=eyJpIjoiYzQxOGIzOGQ3YzcxNDcxZmIwOThlMzZhY2M4MjVkYWUiLCJwIjoiaiJ9)

## Description - what does this code do?
This PR adds two new PageBuilder components with pagination: News and Events.

## Testing done - how did you test it/steps on how can another person can test it 
### Events

### News

## Screenshots, Gifs, Videos from application (if applicable)

## Link to mock-ups/mock ups (image file if you have it) (if applicable)

## Acceptance criteria
- [ ]

## Definition of done
- [x] Unit tests written (if applicable)
- [ ] e2e/accessibility tests written (if applicable)
- [ ] Events are logged appropriately
- [ ] Documentation has been updated, if applicable
- [x] A link has been provided to the originating JIRA issue
- [ ] No sensitive information (i.e. PII/credentials/internal URLs/etc.) is captured in logging, hardcoded, or specs

2022-09-29 17:41 UTC, bradjohnson92008 commented
Hey Camille - FYI.. your migration for page_event_components should be plural.  This one always gets me as well.. as I'm very used to table names being singular... lol.  
![image](https://user-images.githubusercontent.com/60527788/193104002-2462ca9a-78d1-4f24-87e8-e926c5ff1fa5.png)

2022-10-04 00:27 UTC, bradjohnson92008 reviewed
Disregard my previous comment about the card styleing and field... i think I was looking at the wrong figma page.. but I see the latest designs in "Designs with Content" for the "News" and "Events" pages and they look good.  One thing I tested and this may be "**By Design**" is that if I add an "Event" component below a page that has "Events" first... then "News" ... I was expecting that last Event component to display under the "News" but it's added to the List of "Events" in the upper section.. again - which may be fine.. just calling that out.

2022-10-06 19:19 UTC, camillevilla commented
@JoshingYou1 just FYI re: Brad's comment - this is by design for MVP.

> Disregard my previous comment about the card styleing and field... i think I was looking at the wrong figma page.. but I see the latest designs in "Designs with Content" for the "News" and "Events" pages and they look good. One thing I tested and this may be "**By Design**" is that if I add an "Event" component below a page that has "Events" first... then "News" ... I was expecting that last Event component to display under the "News" but it's added to the List of "Events" in the upper section.. again - which may be fine.. just calling that out.

2022-10-07 01:18 UTC, JoshingYou1 requested changes
Great work on this Camille! The pagination stuff is working great 😄 I left some comments, but I also have a few potential bugs to report.

1. If the user doesn't add a URL to either events or news, the element is still created and the `usa-link` and `usa-link--external` classes are added to it.
![](https://user-images.githubusercontent.com/34111449/194445757-9f58dce0-7c03-4fe8-adff-eb55a4d8febe.png)

2. If the user doesn't enter a date for the `published_date`, the app breaks, producing the following error:
![](https://user-images.githubusercontent.com/34111449/194445872-20075b96-6bb2-4ea2-bcc1-80d4d9666e86.png)
3. Should users be able to enter any URL they want to, without validation on at least the backend? I was able to create the link below:
![](https://user-images.githubusercontent.com/34111449/194445968-c73b6e88-f7d3-4f75-a82e-a4e09922df8a.png)

2022-10-07 01:18 UTC, JoshingYou1 commented on app/helpers/application_helper.rb
> +    classes.join(" ")
I think this method can be simplified quite a bit. Perhaps something like this:
```
"usa-link#{' usa-link--external' if !is_internal_link?(url)}"
```

2022-10-07 20:06 UTC, camillevilla commented on app/controllers/page_controller.rb
> +    page_components.each_with_index do |pc, index|
Good point! I'll get rid of those.

2022-10-07 20:26 UTC, camillevilla commented on app/helpers/application_helper.rb
> +  end
Definitely! I'll throw one on.

2022-10-11 14:26 UTC, camillevilla commented
@bradjohnson92008 @JoshingYou1 This PR is ready for re-review.

2022-10-11 18:52 UTC, camillevilla commented
Got it! Thanks @JoshingYou1. Just pushed up a commit for that CSS fix.

2022-10-11 19:50 UTC, bradjohnson92008 approved these changes
Great Work Camille.

2022-10-11 20:40 UTC, merged