DM-3560: Updated crisis line modal styling and info
department-of-veterans-affairs/diffusion-marketplace pull request #561
Opened 2022-12-01 21:18 UTC by JoshingYou1

### JIRA issue link
https://agile6.atlassian.net/browse/DM-3560

## Description - what does this code do?
Makes a few style and content changes to the crisis line modal. Refer to the JIRA link for the content changes.

## Testing done - how did you test it/steps on how can another person can test it 
1. Visit the homepage. Click on the crisis line modal button at the top right of the page. Make sure the styles match the Figma designs. **Changes based on design's feedback:** External links can have the external link styling (the arrow icon at the end of the link). The period at the end of the `Get more resources at...` line should be removed, due to having the external link icon.

## Screenshots, Gifs, Videos from application (if applicable)
![](https://user-images.githubusercontent.com/34111449/205161017-d3c653a6-bb6d-4489-909b-dea897c68aeb.png)

## Link to mock-ups/mock ups (image file if you have it) (if applicable)
https://www.figma.com/file/dkvSpADVqwN5KKByF1TVIa/Design-System---VA-DM?node-id=1305%3A3&t=Qb6SB63cNW5OlNfH-0

## Acceptance criteria
- Devs build phone # and chat changes
- Have design review
- Release to all three environments

## Definition of done
- [ ] Unit tests written (if applicable)
- [ ] e2e/accessibility tests written (if applicable)
- [ ] Events are logged appropriately
- [ ] Documentation has been updated, if applicable
- [X] A link has been provided to the originating JIRA issue
- [X] No sensitive information (i.e. PII/credentials/internal URLs/etc.) is captured in logging, hardcoded, or specs

2022-12-06 20:17 UTC, bradjohnson92008 approved these changes
LGTM Thanks Josh!

2022-12-07 00:19 UTC, camillevilla requested changes
This is looking good, @JoshingYou1! Can you make two small tweaks to the `aria-label` for the phone line and text number? Right now the numbers in the `<a>` text aren't getting read out to screenreaders because  the `aria-label` is overriding it. Adding the numbers will make it easier if a user wants to record the numbers and contact the crisis line on a different device.

2022-12-07 00:19 UTC, camillevilla commented on app/views/shared/_veterans_crisis_line_modal.html.erb
> +              <a href="tel:988" aria-label="Call the Veterans Crisis Line" class="usa-link">
```suggestion
              <a href="tel:988" aria-label="Call the Veterans Crisis Line, Call 988 and select 1" class="usa-link">
```

2022-12-07 00:19 UTC, camillevilla commented on app/views/shared/_veterans_crisis_line_modal.html.erb
> +              <a href="sms:838255" aria-label="Text the Veterans Crisis Line" class="usa-link">
```suggestion
              <a href="sms:838255" aria-label="Text the Veterans Crisis, Text 838255" class="usa-link">
```

2022-12-07 19:54 UTC, JoshingYou1 commented on app/views/shared/_veterans_crisis_line_modal.html.erb
> +              <a href="tel:988" aria-label="Call the Veterans Crisis Line" class="usa-link">
Done!

2022-12-07 19:54 UTC, JoshingYou1 commented on app/views/shared/_veterans_crisis_line_modal.html.erb
> +              <a href="sms:838255" aria-label="Text the Veterans Crisis Line" class="usa-link">
Done!

2022-12-07 20:00 UTC, camillevilla approved these changes
🎶Music to my ears 😎

2022-12-07 23:27 UTC, merged