Dm 3738
department-of-veterans-affairs/diffusion-marketplace pull request #577
Opened 2023-01-25 19:20 UTC by JoshingYou1

### JIRA issue link
https://agile6.atlassian.net/browse/DM-3738

## Description - what does this code do?
Address issues with certain facilities in the `va_facilities.json` having no complexity and being duplicates of facilities that already exist.

## Testing done - how did you test it/steps on how can another person can test it 
1. Open up a rails console: `rails c`, and run the following script: 
```
VaFacility.where(fy17_parent_station_complexity_level: '').destroy_all
```
2. That should have deleted the duplicate facilities in your DB.
3. Now visit `/diffusion-map` and make sure the map loads with no errors. Also, in the filters dropdown, make sure all complexity level checkboxes are formatted as "Level type" (Level description), e.g., 1A (High complexity).
4. Now, update the existing Stockton VA Clinic facility with the data from the json. Run the following script:
```
VaFacility.find_by(slug: '').update(sta3n: '612', station_number: '612QE', classification: 'Other Outpatient Services (OOS)', classification_status: 'Firm', mobile: 'No', parent_station_number: '612A4', official_parent_station_name: 'Sacramento VA Medical Center', fy17_parent_station_complexity_level: '1b-High Complexity', operational_date: '7/1/2022', date_of_first_workload: '10/1/2021', after_hours_phone_number: '[800-382-8387](tel:8003828387) x', pharmacy_phone_number: '[866-600-8279](tel:8666008279) x', enrollment_coordinator_phone_number: '[916-843-7225](tel:9168437225) x', patient_advocate_phone_number: '[916-843-7034](tel:9168437034) x', va_secretary_10n_approved_date: '5/20/2022', planned_activation_date: '7/1/2022', station_number_suffix_reservation_effective_date: '7/1/2022', latitude: 37.88266367.to_f, longitude: -121.2819955.to_f)
```
5. Go to any facility show page and make sure the word "veterans" in the blurb below the name of the facility is now capitalized.

## Screenshots, Gifs, Videos from application (if applicable)
###Diffusion map filters
![](https://user-images.githubusercontent.com/34111449/214664948-9cd96245-ec8b-4fda-bead-1ad695ff9c2f.png)
### Facility show page blurb
![](https://user-images.githubusercontent.com/34111449/214664973-ee5d442e-a6cb-43a6-88b4-788f07dbf823.png)

## Link to mock-ups/mock ups (image file if you have it) (if applicable)

## Acceptance criteria
- [ ]

## Definition of done
- [ ] Unit tests written (if applicable)
- [ ] e2e/accessibility tests written (if applicable)
- [ ] Events are logged appropriately
- [ ] Documentation has been updated, if applicable
- [X] A link has been provided to the originating JIRA issue
- [X] No sensitive information (i.e. PII/credentials/internal URLs/etc.) is captured in logging, hardcoded, or specs

2023-01-25 22:44 UTC, JoshingYou1 commented on app/views/va_facilities/_index_table_row.html.erb
> +        </td>
Cleaned up code a bit.

2023-01-25 22:45 UTC, JoshingYou1 commented on app/views/va_facilities/show.html.erb
> +        facility and serves Veterans in <%= @va_facility.mailing_address_city %>.<%= " This facility opened in #{facility_opening_date.to_s[0..3]}." if facility_opening_date.present? %>
Cleaned up code a bit.

2023-01-25 22:45 UTC, JoshingYou1 commented on lib/tasks/va_facilities.rake
> +                  official_parent_station_name: vaf["Official Parent Station Name"],
We were looking for the wrong key name in the json

2023-03-02 19:35 UTC, bradjohnson92008 requested changes
So it looks like the console commands and rails create_or_update task all ran correctly.. but I"m still seeing the issue with loading the maps - seeing this javascript loading without a call back... and reference ot the deprecated addDomListener method... 
![image](https://user-images.githubusercontent.com/60527788/222533714-ac7bbf5c-1f52-498f-ba49-c2ac88fd3e80.png)

2023-03-10 00:24 UTC, camillevilla approved these changes
Took this for a spin in local with master rebased on top. Things are working great and I definitely see some of the cleanup in the views logic. Great work! Let's get this deployed tomorrow.

2023-03-10 17:19 UTC, merged