Dm 3935 three column pb component
department-of-veterans-affairs/diffusion-marketplace pull request #622
Opened 2023-06-30 20:24 UTC by PhilipDeFraties

### JIRA issue link

https://agile6.atlassian.net/browse/DM-3935

## Description - what does this code do?

Adds new three-column text page-builder component

## Testing done - how did you test it/steps on how can another person can test it 

1. As admin create a page, add Triple Body Text component
2. Fill in title and body for each text field

## Screenshots, Gifs, Videos from application (if applicable)

## Link to mock-ups/mock ups (image file if you have it) (if applicable)

![Screenshot 2023-06-30 at 2 24 00 PM](https://github.com/department-of-veterans-affairs/diffusion-marketplace/assets/65036872/e006ca20-477c-4b3d-a699-69a638c734e2)

## Acceptance criteria
- [ ]

## Definition of done
- [ ] Unit tests written (if applicable)
- [ ] e2e/accessibility tests written (if applicable)
- [ ] Events are logged appropriately
- [ ] Documentation has been updated, if applicable
- [ ] A link has been provided to the originating JIRA issue
- [ ] No sensitive information (i.e. PII/credentials/internal URLs/etc.) is captured in logging, hardcoded, or specs

2023-06-30 20:32 UTC, PhilipDeFraties commented
There are a few things in the acceptance criteria that I don't have an understanding of just yet.. 

are the "e2e/accessibility tests" something that can be addressed in unit test files or is there an established method in existing feature tests?

I'm not entirely sure what is meant by "events logged properly"..

As for documentation, is there documentation somewhere that I can add to regarding the new additions? Happy to do so, also happy to get on a call if you don't feel like typing a response :slightly_smiling_face:


![Screenshot 2023-06-30 at 2 24 53 PM](https://github.com/department-of-veterans-affairs/diffusion-marketplace/assets/65036872/ca87f3bb-ade7-4cac-bb4f-25c7bda69af4)

2023-06-30 20:36 UTC, PhilipDeFraties commented on app/models/page_triple_paragraph_component.rb
> +class PageTripleParagraphComponent < ApplicationRecord
I am not married to this class name, I went with it because it is similar to the existing `PageParagraphComponent`

2023-07-03 19:33 UTC, PhilipDeFraties commented on app/admin/pages.rb
> +              end
this seems a bit redundant considering the validators on the model

2023-07-03 22:19 UTC, camillevilla requested changes
Thanks, Phil! Just a few minor tweaks and I think this is good to go.

2023-07-03 22:21 UTC, camillevilla commented on app/views/page/show.html.erb
> +                    <p><%= component.text3.html_safe %></p>
@PhilipDeFraties hmm maybe hold off on this one until we get feedback from Becca re: how configurable she wants this component to be. https://agilesix.slack.com/archives/CC49Y797U/p1688420165271319

2023-07-06 20:02 UTC, camillevilla approved these changes
Looks great, @PhilipDeFraties! Thanks for making those changes.

2023-07-06 20:03 UTC, merged