DM-4398 update homepage welcome banner styling
department-of-veterans-affairs/diffusion-marketplace pull request #770
Opened 2024-01-17 23:40 UTC by PhilipDeFraties

### JIRA issue link
https://agile6.atlassian.net/browse/DM-4398

## Description - what does this code do?
updates welcome banner on homepage to be in line with 2024 redesign

## Testing done - how did you test it/steps on how can another person can test it 
verify the layout mirrors the figma desing: https://www.figma.com/file/ccwLbt94U9QGfnuFCwOXzY/Core-Designs---VA-DM?type=design&node-id=10914-1114&mode=design&t=yg4Ih9zR6Izf89cY-0

## Screenshots, Gifs, Videos from application (if applicable)
![Screenshot 2024-01-17 at 4 40 15 PM](https://github.com/department-of-veterans-affairs/diffusion-marketplace/assets/65036872/b488e210-9fa0-44be-958b-3f099af63247)

## Link to mock-ups/mock ups (image file if you have it) (if applicable)

## Acceptance criteria
- [ ]

## Definition of done
- [ ] Unit tests written (if applicable)
- [ ] e2e/accessibility tests written (if applicable)
- [ ] Events are logged appropriately
- [ ] Documentation has been updated, if applicable
- [ ] A link has been provided to the originating JIRA issue
- [ ] No sensitive information (i.e. PII/credentials/internal URLs/etc.) is captured in logging, hardcoded, or specs

2024-01-18 23:57 UTC, camillevilla requested changes
Good first pass on this, @PhilipDeFraties. I appreciate your diligence on cleaning up SCSS for removed components. Take a closer look at the mobile designs in Figma for some margin differences we want to address:
![Screenshot_2024-01-18_at_3_19_29_PM](https://github.com/department-of-veterans-affairs/diffusion-marketplace/assets/5402927/375341c2-0b91-4351-860b-13144e79dbe3)

In case it's hard to grok all the suggested changes via comments, here's the markup snippet I ended up with to address the side margins:
```html
<section class="homepage-welcome-banner usa-section padding-top-3 padding-bottom-7" role="region" aria-label="Homepage welcome banner">
    <div class="grid-container">
      <div class="grid-row flex-justify-center text-white text-center">
          <h1 class="grid-col-12 usa-prose-h1">
            Discover VA innovations to adopt at your facility
          </h1>
        <div class="homepage-welcome-banner-body-text-container grid-col-12 desktop:grid-col-9">
            <p class="usa-prose-body margin-top-1">
              We’re a discovery and collaboration tool that curates VA’s promising innovations, encourages their diffusion, and fosters engagement with greater healthcare communities.
            </p>
          </div>
      </div>
    </div>
  </section>
 ```
![Screenshot 2024-01-18 at 3 57 15 PM](https://github.com/department-of-veterans-affairs/diffusion-marketplace/assets/5402927/a591ba16-9768-4eb3-b738-82239487988c)

Some general tips:
1. As much as possible, try to avoid nesting `grid-col-x` divs within other `grid-col-x` divs. 
2. if you find yourself struggling with margins, play around more with some flexbox utilities so we can avoid calculating whitespace. Try to avoid `grid-offset-x` moving forward. 

After we're done, let's also pass this over to Nick for some design review.

2024-01-18 23:57 UTC, camillevilla commented on app/assets/stylesheets/dm/pages/_home.scss
> +    background: #162E51;
Nice cleanup on this section. This matches the footer color, which uses `.bg-primary-darker`. Let's use the utility class on the HTML element

2024-01-18 23:57 UTC, camillevilla commented on app/views/home/index.html.erb
> +      <div class="grid-row">
```suggestion
      <div class="grid-row text-center text-white flex-justify-center">
```
1. Set the `text` properties up here so you don't have to specify per element
2. use USWDS flexbox properties and you can remove the `grid-col-offset-1` and other margin properties on the `<p>` tag. As much as possible, we want USWDS and the automagic of flexbox to do the heavy lifting on calculating margins for us.

2024-01-18 23:57 UTC, camillevilla commented on app/views/home/index.html.erb
> +          <h1 class="usa-prose-h1 text-white">
```suggestion
          <h1 class="usa-prose-h1">
```

2024-01-18 23:57 UTC, camillevilla commented on app/views/home/index.html.erb
> +          <div class="grid-row">
remove this extra `grid-row` and make `homepage-welcome-banner` a sibling of the header

2024-01-18 23:57 UTC, camillevilla commented on app/views/home/index.html.erb
> +              <p class="usa-prose-body text-white margin-top-1 text-center desktop:margin-x-0 mobile:margin-x-2 tablet:margin-x-4">
See comment above
```suggestion
              <p class="usa-prose-body margin-top-1">
```

2024-01-18 23:57 UTC, camillevilla commented on app/views/home/index.html.erb
> +            <div class="homepage-welcome-banner-body-text-container grid-col-9 grid-offset-1 ">
```suggestion
            <div class="homepage-welcome-banner-body-text-container grid-col-12 desktop:grid-col-9">
```
See screenshot in parent comment. Let's collapse the side margins on this text when we're in mobile and tablet widths. Note that USWDS assumes mobile is the default width (`grid-col-12`). You can use `desktop:grid-col-9` to define the desire behavior for desktop.

2024-01-22 23:35 UTC, PhilipDeFraties commented on app/views/home/index.html.erb
> +  <section class="usa-section padding-top-3 padding-bottom-7 bg-primary-darker" role="region" aria-label="Homepage welcome banner">
@camillevilla just went ahead and removed the `homepage-welcome-banner` css classes

2024-01-23 22:23 UTC, camillevilla requested changes
One more bit of markup to get alignment right in responsive: 
### Before
![Screenshot 2024-01-23 at 2 23 15 PM](https://github.com/department-of-veterans-affairs/diffusion-marketplace/assets/5402927/9c73d62f-4144-469c-9685-b0197192fa90)

### After
![Screenshot 2024-01-23 at 2 23 06 PM](https://github.com/department-of-veterans-affairs/diffusion-marketplace/assets/5402927/173b52e6-d7ad-4555-8433-97ef79f1ff5f)

2024-01-23 22:23 UTC, camillevilla commented on app/views/home/index.html.erb
> +            <p class="usa-prose-body margin-top-1">
```suggestion
            <p class="usa-prose-body margin-top-1 text-center">
```

2024-01-23 22:36 UTC, camillevilla approved these changes
✅ Looking good! Let's get this out to DEV for one more visual design review from Nick.

2024-01-25 16:40 UTC, merged